allowBuilds:
  better-sqlite3: true
  esbuild: false

overrides:
  rollup@>=4.0.0 <4.59.0: 4.59.0
  minimatch@<3.1.4: 3.1.4
  ajv@<6.14.0: 6.14.0
  minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
  minimatch@>=9.0.0 <9.0.7: ">=9.0.7"
