export {
  MagnifyingGlassIcon as SearchIcon,
  Cog6ToothIcon as SettingsIcon,
  ChevronDownIcon,
  PlusIcon,
  CheckIcon,
  ArrowPathIcon as RefreshIcon,
  ArrowTopRightOnSquareIcon as ExternalLinkIcon,
  CloudArrowUpIcon as CloudUploadIcon,
  MusicalNoteIcon,
  SparklesIcon,
  Squares2X2Icon as DiscoverIcon,
  EyeSlashIcon,
  PlayIcon,
  PauseIcon,
  UserCircleIcon,
  ArrowRightStartOnRectangleIcon as LogoutIcon,
} from "@heroicons/react/20/solid";
