import type { PromotedAlbumSettings } from "./settingsContextDef";

export const DEFAULT_PROMOTED_ALBUM: PromotedAlbumSettings = {
  cacheDurationMinutes: 30,
  profileTtlMinutes: 1440,
  topArtistsRange: "6months",
  topArtistsCount: 10,
  pickedArtistsCount: 3,
  tagsPerArtist: 5,
  deepPageMin: 2,
  deepPageMax: 10,
  genericTags: [
    "seen live",
    "favorites",
    "favourite",
    "my favorite",
    "love",
    "awesome",
    "beautiful",
    "cool",
    "check out",
    "spotify",
    "under 2000 listeners",
    "all",
  ],
  libraryPreference: "prefer_new",
  explorationRate: 0.5,
  exploreCandidateCount: 12,
  genreOverlapThreshold: 0.15,
  backgroundRegenEnabled: true,
  backgroundRegenIntervalMinutes: 60,
  backgroundRegenActiveWithinMinutes: 10080,
};
